ureportdb:
  image: "postgres:9.4"
  environment:
      POSTGRES_DB: "ureport"

ureportredis:
    image: "redis"

ureport:
  build: .
  volumes:
      - ./:/code
  environment:
      ENV: "dev"
      RDS_HOSTNAME: "ureportdb"
      RDS_USERNAME: "postgres"
      RDS_PASSWORD: ""
      RDS_PORT: "5432"
      RDS_DB_NAME: "ureport"
      REDISHOST: "ureportredis"
      STATIC_DIR: "/var/www/static/"
      HOSTNAME: "ureport-local.eocng.org"
  command: start 
  ports:
    - "80:80"
    - "8000:8000"
  links:
    - ureportdb
    - ureportredis
